// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectManagement.Infra.Configurations;

#nullable disable

namespace ProjectManagement.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectManagement.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7007a3ac-d496-4f8b-84fd-22cd72910938"),
                            AccessType = 1,
                            Name = "Leandro Vilas Boas"
                        },
                        new
                        {
                            Id = new Guid("9991d6cb-dd0e-4ffe-ab1f-c67b6babe9cf"),
                            AccessType = 1,
                            Name = "Thais Vilas Boas"
                        },
                        new
                        {
                            Id = new Guid("ae4b6e28-67ad-4b07-a9cd-6f7e5a0af6cc"),
                            AccessType = 1,
                            Name = "Mariana Vilas Boas"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
